import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nasza apka.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex justify-center mt-2 space-x-4">
            <li>
              <ActiveLink href="/">Home</ActiveLink>
            </li>
            <li>
              <ActiveLink href="/products">All</ActiveLink>
            </li>
          </ul>
        </nav>
        <section className="mx-auto max-w-md p-12 sm:max-w-2xl md:max-w-4xl lg:max-w-7xl">
          {children}
        </section>
        <footer>
          <p className=" text-center text-sm text-gray-500">© 2024</p>
        </footer>
      </body>
    </html>
  );
}
``;
